### ISSUE TITLE
Inquiry About Sample in Fig. 3: Generated 3D CT Volumes

### ISSUE THREAD

**Issue by VinyehShaw** [ibrahimethemhamamci/GenerateCT#15]
Dear Authors,

I am very interested in your work, and I appreciate the insights it provides. Since I could not find public access to Google Imagen and the fine-tuned Stable Diffusion model referenced in your paper, I would like to directly cite the experimental images presented in Fig. 3 of your work: axial, sagittal, and coronal slices of 3D CT volumes generated by various methods based on the text prompt "26 years old male: Findings compatible with COVID-19 pneumonia."

Could you kindly let me know the corresponding sample ID in the CT-Rate dataset for the specific example shown in Fig. 3? @sezginerr 

Thank you very much for your assistance.

**Comment by sezginerr** [comment]
Hi @VinyehShaw ,

Yes sure, I will check and inform you. Regarding the fig. 3 they are not publicly trained models. We have trained them for CT generation as a comparison. If you need weights of those models I can also check and send them.

**Comment by VinyehShaw** [comment]
> Hi @VinyehShaw ,
> 
> Yes sure, I will check and inform you. Regarding the fig. 3 they are not publicly trained models. We have trained them for CT generation as a comparison. If you need weights of those models I can also check and send them.

Thank you very much for your prompt response @sezginerr . I would greatly appreciate it if you could provide the ground truth for Fig. 3, specifically the training sample ID in the CT-RATE dataset. Additionally, it would be extremely helpful if you could share the generated nii.gz volumes or the original images (without the crosshair) from Fig. 3 for the models, including Imagen, Stable Diffusion, Phenaki, and your method. We plan to cite and compare these results in our work.

Considering the potential size of the volumes, please feel free to share them via a cloud storage link if that would be more convenient.

Thank you once again for your assistance and support.

**Comment by VinyehShaw** [comment]
Hi @sezginerr I hope you’re doing well. I just wanted to kindly follow up on my previous message regarding Fig. 3—are they still available after your check?

Thank you very much for your time, I look forward to your response.

**Comment by VinyehShaw** [comment]
Since no response has been provided, this issue is being closed for now.
