### ISSUE TITLE
Questions on inference stage

### ISSUE THREAD

**Issue by cheliu-computation** [ibrahimethemhamamci/GenerateCT#7]
First thanks for your effort on this amazing work!

Base on the paper, there are three blocks in generateCT(gCT), ViTAE, MaskGiT, SuperresDiffusion. the repo show three seperate script for different blocks, is there any way to pack them into one script to generate CT from only text?

From my rough understanding, ViTAE cannot generate the CT independently, and MaskGit is the key in this pipeline, because it can generate CT from text prompt and random masked token. Then the synthetic CT would feed to the diffusion model for superresolution.

So, in the first script for inference: `python inference_ctvit.py`, what is the input and out for inference? when I run this script it show no data/samples. This autoencoder should not infer to anything if there is no generation here.

When I run the second script `python inference_transformer.py`, there are several error and confused part.
on line 40, `cvivit` is not defined, should it be `ctvit`? I modify that from `cvivit` to `ctvit` to eliminate the error.
https://github.com/ibrahimethemhamamci/GenerateCT/blob/77fafb06bbac2161c0ab3c09dde39ba1a12f476b/inference_transformer.py#LL40C15-L40C15

on line 67, I could not find any code related to `phenaki_model = Phenaki`, so I cannot fix this issue.
https://github.com/ibrahimethemhamamci/GenerateCT/blob/77fafb06bbac2161c0ab3c09dde39ba1a12f476b/inference_transformer.py#L67

On ilne 72, `transformer_model` is also not defined.
https://github.com/ibrahimethemhamamci/GenerateCT/blob/77fafb06bbac2161c0ab3c09dde39ba1a12f476b/inference_transformer.py#L72

For the third script: `accelerate launch \
    --multi_gpu \
    --mixed_precision=fp16 \
    --num_machines=1 \
    train_superres.py --config superres.yaml --stage 2 --bs 8`
I can run it without error message, seems everything is going correctly.

Looking forward to your answer
Thanks a lot!

**Comment by sezginerr** [comment]
Hello @cheliu-computation,

I sincerely appreciate your interest in our work and for bringing the bug to our attention. I want to inform you that the issue has been resolved, and the repository has been updated accordingly. It should now function properly.

Best regards,
Sezgin

**Comment by cheliu-computation** [comment]
It works! Thanks a lot.
