### ISSUE TITLE
Computing resource problem

### ISSUE THREAD

**Issue by daw2021daw** [ibrahimethemhamamci/GenerateCT#9]
- I have limited computing resources, can it work successfully on NVIDIA GeForce RTX 3090?

**Comment by sezginerr** [comment]
Grammar check:

Dear @daw2021daw,

Thank you very much for your interest in our work. Unfortunately, it is not possible to train GenerateCT or perform an inference with the RTX 3090, as the memory will not be sufficient. 

Best regards,
Sezgin
